export const Role = {
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  PATIENT: 'PATIENT',
  NURSE: 'NURSE',
  RECEPTIONIST: 'RECEPTIONIST',
  PHARMACIST: 'PHARMACIST',
  LAB_TECH: 'LAB_TECH',
  RADIOLOGIST: 'RADIOLOGIST',
  ACCOUNTANT: 'ACCOUNTANT',
  INSURANCE_OFFICER: 'INSURANCE_OFFICER',
} as const;

export type RoleType = (typeof Role)[keyof typeof Role];